##########################################
## Configuration file for all enemies ####
##########################################

SHOT_PROJECTILE_SPEED = 0.05

ULTRA_FAST_SPEED = 1
FAST_SPEED = 2
NORMAL_SPEED = 3
MEDIUM_SPEED = 4
SLOW_SPEED = 5
VERY_SLOW_SPEED = 6

MELEE_ATTACK_RANGE = 1

# WASP
WASP_TRACKING_DISTANCE = 8
WASP_HP = 3
WASP_MELEE_BONUS = 0
WASP_RANGED_BONUS = 0
WASP_AC = 10

#GOBLIN
GOBLIN_TRACKING_DISTANCE = 8
GOBLIN_HP = 100
GOBLIN_MELEE_BONUS = 0
GOBLIN_RANGED_BONUS = 1
GOBLIN_AC = 11
